### ISSUE TITLE
Problem in `make` setup

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#103]
The make setup currently does not consider modifications in nested .tex files. Needs to be fixed asap ...

**Comment by hochleitner** [comment]
What exactly is (not) happening? Are changes not detected?

**Comment by imagingbook** [comment]
Yes, the .tex files in sub-directories are simply not added to the dependency list.

**Comment by imagingbook** [comment]
Fixed by commit ded8f518e5241a4c238411761e4a6aaf2e33d208.
Documents are now only rebuilt (processed with LaTeX and zipped) if any of the contributing .tex, .sty, .cls or image files was modified. Document zipping was moved from `makefile` to ' makefile-latex` to make use of the existing dependency check.
