### ISSUE TITLE
Harmonize software setup

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#107]
The thesis tutorial currently contains recommendations for software at different locations:
- `latex.tex` has a "Software" section
- `anhang_a.tex` has the "Allgemeine technische Voraussetzungen" and "Verwendung unter Windows/Mac OS" sections.
- `drucken.tex` also references on the IDE (TeXnicCenter) when related to printing.

I suggest keeping the technical details in the appendix and reference it at the beginning of the "Arbeiten mit LaTeX" chapter. Something like "for technical details and a possible setup, please refer to Appendix A."

I would also suggest removing all the information TeXnicCenter + Sumatra parts. I know you're still using it, @imagingbook. I do, however, think that most people are better off with an all-in-one solution such as TeXstudio, which requires no particular configuration. Plus, some of the things mentioned in the document (such as the sumatra-utf8 tco file) aren't in the repository anymore (at least I can't seem to find it).

We can, of course, put in a list of possible IDEs, but I'd still add one recommended configuration for those who don't want to deal with selecting between several different tools.

But since this is somewhat of a fundamental content change, I'd like to discuss this here before proceeding.

**Comment by imagingbook** [comment]
Definitely - pls. go ahead and clean up this mess!

**Comment by hochleitner** [comment]
Aye aye, sir. I'll get at it right away.

I'll propose the changes to the document in a pull request (without the rebuild). Once we're satisfied, we can run the rebuild.

**Comment by imagingbook** [comment]
Very well, I like the spirit ...

**Comment by imagingbook** [comment]
This was fixed by commit dfc42465ddad8ddf87f176484c9d1d864e4bf497. No need for a full rebuild (CTAN contents got updated with commit c427c9eb67ccb5b940f43d8f2ba866b0ee69d8ed).
