### ISSUE TITLE
Duplicate files in CTAN submission

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#111]
The CTAN administrators complained that the `examples` directory contained duplicate files. They suggested to put them in a single location and use symbolic links to reference them. Since symbolic links do not work across platforms (particularly under Windows) I recommend NOT to follow this advice but remove the examples from CTAN alltogether (they can be found on GitHub anyways).

**Comment by hochleitner** [comment]
Yes, I agree. I hardly doubt that anyone is actually grabbing our template documents from deep within their LaTeX distribution structure.

**Comment by imagingbook** [comment]
The `examples` directory has been removed from the CTAN release (new version not submitted yet).
