### ISSUE TITLE
Incorporate the usage of APA citation style into the package and documents

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#114]
The usage of the [APA citation style in its 7th edition](https://apastyle.apa.org/products/publication-manual-7th-edition) is a widely requested feature. The following things need to be adapted/added.

- Make the switching of citation styles easier: add a document option that sets the appropriate style in `hgbbib.sty`.
- Create a section in `HgbThesisTutorial` that explains the necessary steps when using APA along with a few short examples.
- Add an additional, ready-to-use document (e.g., `HgbThesisDE-APA` and maybe `HgbThesisEN-APA`) with everything set up for APA.

`HgbThesisTutorial` itself will not be "converted" to APA since the need for additional citation macros with the APA style would mean that all the citations need to be replaced. This, in turn, would mean maintaining two separate tutorial documents, which need to be kept in sync.

Please add any ideas and suggestions below. This will be done throughout the Christmas holidays and should be available for the coming summer semester.

**Comment by imagingbook** [comment]
Branch `apa-switch` now contains a document option `apa` which switches the biblatex-style in `hgbbib.sty`. The CTAN manual has been updated accordingly. Please test and add a section in the tutorial as planned (I stronly agree that the tutorial itself should not be switched to APA).

**Comment by imagingbook** [comment]
The above changes are in the master branch now (by PR https://github.com/Digital-Media/HagenbergThesis/pull/115), branch `apa-switch` has been removed.

**Comment by hochleitner** [comment]
Okay, so this took waaaay longer for me to write than I'd like to admit. But there's PR #116 out there containing two new, APA-based base-documents for HgbThesis and has a section in the HgbThesisTutorial that explains how to use APA and gives some examples.
@imagingbook, please look at it and adapt/expand if you feel something's missing or should be done differently.

**Comment by imagingbook** [comment]
Done by commit 29c54e294fff40de43d3b4cd1e4bcb9336877e12
