### ISSUE TITLE
Hinweis auf häufige Fehler im Quellenverzeichnis

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#12]
- Vorsicht beim Download von BibTeX-Daten -- die sind meistens fehlerhaft. Nicht blind übernehmen!!
- Groß-Kleinschreibung in Titeln, Konferenznamen etc., Anordung von Konferenznamen.
- Journal-Namen grundsätzlich ausschreiben.
- Auf Konsistenz bei Ortsangaben, Verlagen etc. achten!

**Comment by hochleitner** [comment]
Die konsistente Groß/Kleinschreibung könnte theoretisch auch der Style der Bibliographie handhaben, oder?
Bei Ortsangaben stelle ich mir immer die Frage, wie mit den Ländern bzw. auch Bundersländern/Staaten umzugehen ist. Schreibe ich?
- Bonn, Deutschland
- Bonn
- Bonn, NRW, Deutschland

Für deutschsprachige Bücher finde ich letzteres seltsam, jedoch sieht man bei Englischen ja oft sowas wie Sebastopol, CA, USA.

Die Frage ist, soll das einheitlich gehandhabt werden oder gibt es Unterschiede in deutschen und englischen Ortsangaben?

**Comment by imagingbook** [comment]
More or less fixed by commit df6494a0e82301653a222332945d4135f8c0c11f.
