### ISSUE TITLE
Replace year and month in Biblatex entry examples with date

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#124]
Section 2.3.9 of the [Biblatex Manual](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf) states: 

> The fields `year` and `month` are still supported by `biblatex`, but the full set of date features (day and time precision, ranges, …) can only be used with `date`. It is therefore recommended to prefer `date` over `year` and `month` unless backwards compatibility of the `bib` file with classical BibTeX is required.

I, therefore, suggest replacing all occurrences of `year` and `month` in the examples in HgbThesisTutorial in section 6.3 and in the bib file with `date`. If there are no objections, I'll proceed with this (if there are any, please comment below).

**Comment by imagingbook** [comment]
No objections here. I suppose must publishers still use the traditional scheme for compatibility reasons (and will do so for some time). I have not tested this, but as long as the old format still works with `biblatex` we should be OK.
