### ISSUE TITLE
`smartquotes` not working on title page

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#136]
The `smartquotes` option does not affect anything entered in the title page macros. While probably expected, students came to rely on the option and therefore a lot of documents are handed in with the wrong quotes in the title.

Applying the smart quotes to the title page would be beneficial.

**Comment by imagingbook** [comment]
Apparently quote substitution by `csquotes` gets activated at `\begin{document}` only. Thus a simple solution is to place `\begin{document}` _before_ `\title{...}` to make `smartquotes` work inside the title as well. I suggest to make this change in the template.
Alternatively, one could use `\enquote{...}` in the title and leave everything else unchanged.

**Comment by hochleitner** [comment]
I ran some tests, and as far as I can tell, it makes no difference if the `\title`, `\author`, and all our other commands are placed before or after `\begin{document}`. The file builds just fine, and the meta-data set by `hyperref` is also okay in the final PDF.

I suggest moving the definitions after `\begin{document}` because many students use quotes in their titles. Since they rely on smart quotes, I've seen printed theses with ugly quotes on the title page (the curse of making things easier).

Should we encounter a package that needs this data set in the preamble, we can always re-evaluate which is more important.

I'll open a PR with the necessary changes.
