### ISSUE TITLE
Consider Booktabs for Tables

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#138]
Stephan Dreiseitl suggested that we take a look at the [Booktabs](https://ctan.org/pkg/booktabs) package for typesetting the tables in the thesis tutorial document.

Here are some arguments why this might be a good idea: https://nhigham.com/2019/11/19/better-latex-tables-with-booktabs/

I'm not much of an expert in this matter, but these tables do have a more clean look, and it seems like publishers are using them.

In the course of this, it might also be a good idea to include multicolumn and multirow since these are used quite often.

**Comment by imagingbook** [comment]
Sure, `booktabs` adds some helpful features (I have been using it myself). Personally I don't consider its look a great improvement over the original LaTeX table layout (which is admittedly poor). I agree that vertical rules are often unnecessary but the strict recommendation against I find too extreme. (And they look really bad when used with `booktabs`.) So I guess I am uncertain what to suggest ...

**Comment by hochleitner** [comment]
I'm no expert myself, but from what Stephan suggested, vertical rules are something you want to avoid. I'll look at the package and experiment with it in a branch. Then we can decide if we like it or not.

**Comment by imagingbook** [comment]
Good idea. I hope you can find a better table example than the one we have now ;-)
