### ISSUE TITLE
Build of HgbThesisTutorial fails due to \verbatiminput

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#139]
The build of `HgbThesisTutorial` fails with many error messages on all of my local MikTeX setups: three Windows/MikTeX and one Mac OS/MacTeX setup. All with the latest package updates. The build on Overleaf still works.

![latexerror](https://user-images.githubusercontent.com/2236807/201036004-568de200-71ec-44df-a154-fb11b87aac23.png)

It turns out the culprit is this line:
https://github.com/Digital-Media/HagenbergThesis/blob/9f9b9c38f9db802adffcff5c88623594ce6a2250/documents/HgbThesisTutorial/back/anhang_d.tex#L21

When it's disabled, the document builds fine.

Nothing has changed on our side, so the error is probably from the `verbatim` package or the `latex-tools` package, where `verbatim` is contained. There has been a new release on 2022-11-01; maybe this broke something.

The issue seems to be that `\vebatiminput` can't include the file that's been processed right now because if I copy `main.tex` to a new file (e.g., `maincopy.tex`), I can include this one without issues. So there's nothing within the file that makes `\verbatiminput` fail.

@imagingbook, could you try on your local setup(s) and see if this also happens for you? To reproduce, upgrade all packages of your TeX distro, remove all auxiliary files and then build `HgbThesisTutorial`.

If this is the case, we have multiple options on how to deal with this:
1. Remove `anhang_d.tex` altogether.
2. Include another file and not `main.tex` in `anhang_d.tex` (e.g., `hgb.sty` or something similar).
3. Switch to the [`fancyvrb`](https://ctan.org/pkg/fancyvrb) package and see if it works. The package does have some other nice amenities, such as a short `\verb` syntax, so this might be worth considering anyway.

**Comment by imagingbook** [comment]
Will do ASAP ...

**Comment by imagingbook** [comment]
I cannot confirm this problem on any of my Win7 and Win10 machines, with freshly updated MikTex (22.10). CTAN says that the `verbatim` package was last updated 2020-07-07 (version 1.5u), so the problem should have appeared much earlier I suppose.
Could it be a user-related problem (maybe specific to MacOS)?

**Comment by hochleitner** [comment]
Thanks for testing. So, could this be a client problem? I'm using TeXstudio 4.3.1 with Qt6 on all platforms. 

I just built the document on the console using `latexmk`, and it builds just fine.

But: I also created an MWE in a file called `verbatiminput-mwe.tex` with this content:

```latex
\documentclass[a4paper]{article}
\usepackage{verbatim}

\begin{document}
	\section{I include myself}
	\verbatiminput{verbatiminput-mwe.tex}
\end{document}
```

And this also works just fine. So if TeXstudio can't handle a verbatim input from the same file being processed, then it's more complicated than the above.

I'm still puzzled about what causes this.

**Comment by hochleitner** [comment]
Okay, I think I can reproduce what's happening here. Here's my updated MWE:

File: `verbatiminput-mwe.tex` (main file):
```latex
\documentclass[a4paper]{article}
\usepackage{verbatim}

\begin{document}
	\include{sections/anotherfile}
\end{document}
```

File: `sections/anotherfile.tex` (located in the subdirectory "sections")
```latex
\section{I include myself}
\verbatiminput{verbatiminput-mwe.tex}
```

When building this constellation on the command line (`pdflatex.exe -synctex=1 -interaction=nonstopmode "verbatiminput-mwe.tex"`), it works just fine and shows the section header with the source of the main file.

When I try to build it from within TeXstudio, I get errors that `\section` is an unknown command and `\begin{document}` is missing, since it actually tries to build `anotherfile.tex` instead of the `verbatiminput-mwe.tex`. But this only happens if the included file is in a subdirectory. TeXstudio somehow gets thrown off by this. But it's exactly the configuration we have in the `HgbThesisTutorial`.

Could you maybe try and verify if this happens on your machines too, if you have a TeXstudio installation? If so, I'll file a bug report with them.

**Comment by imagingbook** [comment]
I  had uninstalled ``TeXstudio`` some time back and cannot get the current version to run at all any more (under ``Win7``). The previous version (``texstudio-4.3.0-win-portable-qt5``) runs and throws the same errors as you reported.
I also tried ``TeXworks`` (which also uses ``MikTeX``) and this works fine.

**Comment by hochleitner** [comment]
The QT5 versions of TeXstudio weirdly crash all the time, so QT6 is the better option.

The crash only happens with the subdirectory as far as I can tell. Probably some file resolution issue that breaks the verbatim input.

I'll file a report in the TeXstudio repo. Thanks for testing!

**Comment by imagingbook** [comment]
If the problem persists, perhaps we can simply duplicate the ``main.tex`` file during our ``make`` process?

**Comment by imagingbook** [comment]
OK, I think I found the cause of the problem. It is **not** ``\verbatiminput`` itself but its appearance inside the ``LaTeXCode`` environment in ``anhang_d.tex``. I replaced
```
\begin{LaTeXCode}[numbers=none]
\begin{footnotesize}
\verbatiminput{main.tex}
\end{footnotesize}
\end{LaTeXCode}
```
by
```
\begin{verbatim}
\begin{footnotesize}
\verbatiminput{main.tex}
\end{footnotesize}
\end{verbatim}
```
and things work nicely in TexStudio. Don't know what TexStudio does but it appears to scan ``angang_d.tex`` even before running ``main.tex``. Pls. check if this resolves the issue.

**Comment by hochleitner** [comment]
I cannot confirm this. This issue persists here for me, no matter if a listings or verbatim environment is used.

My MWE from above didn't even include something like this; it's just the pure "include the main file from an inputted file via verbatiminput". And this fails. The subdirectory does not matter though. I have to take that back. It fails either way.

**Comment by imagingbook** [comment]
Odd. What does the logfile say? Does pdflatex get started at all?

**Comment by hochleitner** [comment]
Yes, but with the wrong file. With the one that has the verbatim input in it instead of the main file.

**Comment by imagingbook** [comment]
Wow. Looks like a bug in TexStudio indeed ...

**Comment by hochleitner** [comment]
As suggested in https://github.com/texstudio-org/texstudio/issues/2670#issuecomment-1312502337, setting main.tex as the explicit root document can act as a workaround until this is resolved. I'm closing the issue here since there's not much that can be done from our side.

![image](https://user-images.githubusercontent.com/2236807/201920687-d3767e96-dfd5-491a-a441-922609a2c5b2.png)

**Comment by imagingbook** [comment]
_"Copy the main file under a new name and include it - it works."_
As said, copying the main file during the build process may be another workaround ...

**Comment by imagingbook** [comment]
@hochleitner I tried a quick fix using `\verbatimcopy` to duplicate `main.tex` from within LaTeX itself. Could you check if this works for you? (Not sure about Overleaf.) See branch `verbatiminput-check`.

**Comment by hochleitner** [comment]
For me, it doesn't change anything. TeXstudio still has issues resolving things and tries to build `anhang_d.tex` if `main.tex` is not set as an explicit root.

I wouldn't put much more work into it. The workaround is easy enough and this clearly is an issue with a single client. But if we want this resolved, we can always use one of the other `.tex` files or maybe include a sample code (with Java, PHP or any other code) file for demonstration purposes.
