### ISSUE TITLE
Reduce content and create wiki

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#14]
Shorten introduction, Appendix, etc.

**Comment by hochleitner** [comment]
Put extended information (about additional packages, etc.) into the wiki.

**Comment by hochleitner** [comment]
I created the branch [streamlined-content](https://github.com/Digital-Media/HagenbergThesis/tree/streamlined-content) where I commented out everything that I believe is better off in the wiki than the document. Relevent comments/information are marked with %%%.
This reduced the length of the final PDF by one third. Please have a look and modify as pleased. Discussion can go here.

**Comment by imagingbook** [comment]
Good start, but I think we should take a more radical route. The goal should be to reduce the main (double language) document to 1/3rd (or even less) of the current volume. Some thoughts:
- Supplementary materials should be directly linked from the main text, so readers can access the relevant details immediately. If we use the Github-Wiki for this purpose we need to be very careful about naming pages and keeping links in sync might be difficult in the long run.
- **Alternative idea**: Make a common - English only - Appendix that is included by both (DE/EN) main LaTeX documents. This makes it easy to keep links in sync and also makes the LaTeX source transparent immediately. 
??

**Comment by hochleitner** [comment]
Since the current version contains a streamlined (meaning empty) version and the full example document, I guess this is also not relevant anymore. I will close the issue and remove the branch https://github.com/Digital-Media/HagenbergThesis/tree/streamlined-content as it not up to date anymore.
