### ISSUE TITLE
Remove `ifthen` from `hgblistings.sty`

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#154]
While checking Table 3.2 in `HgbThesisTutorial` I discovered that `hgblistings.sty` includes the package `ifthen` at the very top:

https://github.com/Digital-Media/HagenbergThesis/blob/117e34ec5cc7091e88e591e29c1158d695998e0f/dev/latex/hgblistings.sty#L7-L10

In `hgb.sty`, on the other hand, we include `xifthen`:

https://github.com/Digital-Media/HagenbergThesis/blob/117e34ec5cc7091e88e591e29c1158d695998e0f/dev/latex/hgb.sty#L8-L15

Since `xifthen` builds upon `ifthen` and extends it, I think we're good the remove the inclusion of `ifthen`.

Looking at the `xifthen` source shows that this package does include `ifthen` anyway:

https://github.com/JosselinNoirel/xifthen/blob/49163827d56672509971f2034ec77c72d1d674ed/xifthen.sty#L4-L11

I compiled the tutorial with `ifthen` removed from `hgblistings.sty,` and it worked. Also, because `hgb.sty` always comes before `hgblistings.sty,` I don't think there should be any side effects but I'd like to have a second pair of eyes look over it before breaking something.

**Comment by imagingbook** [comment]
Yes, there don't seem to be any side effects. I fixed this in commit 6d49b635222e042025c45483f470b9362848ea89 by changing `\RequirePackage{ifthen}` in all `hgblistings.sty` files to `\RequirePackage{xifthen}` (no rebuild yet). This has no effect if `hgb.sty` is previously loaded and documents the dependency on that package.
