### ISSUE TITLE
Page numbering is different for the first and following pages in a chapter

### ISSUE THREAD

**Issue by AetherDim** [Digital-Media/HagenbergThesis#161]
Hi there,

I was wondering whether the position of the page number is a bug:

![image](https://github.com/Digital-Media/HagenbergThesis/assets/74829006/82e030ca-2569-44d1-87cc-6931069149ab)

Thanks in advance!

**Comment by AetherDim** [comment]
This problem could be related to:
[positions-of-page-numbers](https://stackoverflow.com/questions/2801107/positions-of-page-numbers-position-of-chapter-headings-chapters-and-table-of-c)

this is a possible workaround:
[workaround](https://tex.stackexchange.com/questions/10043/page-number-position)

**Comment by imagingbook** [comment]
This is _not_ a bug but intended behavior. In the LaTeX standard `book` class setup, positioning of the page number (among other things) is different on the first page of each chapter.
