### ISSUE TITLE
Upgrade CC License

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#19]
The template currently uses CC 3.0 while 4.0 is already available.

I also suggest discussion the kind of CC license used since the current "Non Commerical, "No Derivatives" version is very strict in itself and contradicts the idea behind CC in my opinion. Discussion welcome (see https://creativecommons.org/share-your-work/public-domain/freeworks/ for additional info).

**Comment by imagingbook** [comment]
Main reason for a strict license was to make it easier for authors to accept, since a strict CC license is certainly better than no license. This affects the general public and authors are free to grant weaker conditions to individuals any time.

**Comment by hochleitner** [comment]
The question I was asking myself is: if I'm granting someone rights to modify and even use my work (in this case a thesis) commercially through an very open CC license, does this mean that someone could more or less legally use my thesis as a starting point for their own. Or to put it differently: does this enable people to plagiarize my work without consequences?

**Comment by imagingbook** [comment]
License updated to CC BY-NC-ND 4.0 (international). There is no ported version (never liked the "AT" designation anyway).

**Comment by hochleitner** [comment]
Changed in 4a1bdbea291ca9eae451248dea93ac45554b589a.
