### ISSUE TITLE
Clear out hgb.sty

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#20]
_hgb.sty_, _hgbbib.sty_, _hgbheadings.sty_, _hgblistings.sty_ and _hgbabbrev.sty_ contain many old settings that have been commented out during earlier versions and most likely have been kept for fallback reasons. Removing these lines would make the files smaller. Old settings would still be available in version control anyway.

**Comment by imagingbook** [comment]
Done.

**Comment by hochleitner** [comment]
Fixed in 81f5b75cc41d615189ebd2abe216f9b542f00e2d, 916d3c194557357904118fc45c6170501e47d384, 6edef17d81d0f095977c9f9d836317a8b358fac2, and 39be064a82baf6b2ba0c948b9210881c7677a61a.
