### ISSUE TITLE
Rename praktikum.tex

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#24]
Rename 'praktikum.tex' to 'internship.tex'? Or leave as is, because used in German only?

**Comment by hochleitner** [comment]
What about creating two versions as well? I could imagine that an English version might come in handy for those who do their internships abroad. And if the first bachelor's thesis can be done in English, why not the second as well.

If not I'll rename it to _internship.tex. for consistency's sake.

**Comment by imagingbook** [comment]
I suggest to keep a German-only version for now but to rename the file (for consistency reasons). Changing the setup is easy if anyone insists to write it in English.

**Comment by imagingbook** [comment]
Renamed to "_internship_DE".
