### ISSUE TITLE
Solution for digital content

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#27]
Since burning CDs and DVDs has become quite exotic and putting SD cards or ultra-thin USB drives into a thesis is probably also not a long term solution it might be a good idea to store digital content (source code, reference material, PDF version of the thesis) online and add a link to this storage in the thesis.

While we aim to figure out the "how" and "where" on storing such files, I have proposed a simple addendum to the title pages that adds an additional field in the preamble which holds the URL to the content and uses this URL to generate a QR code as well as a link.
See branch [qrcode-page](https://github.com/Digital-Media/HagenbergThesis/tree/qrcode-page) to give it a try and feel free to modify this approach or suggest something completely different.

Any suggestions on where and how to store these digital files are of course welcome as well (maybe @diephuis has input on this as well).

**Comment by imagingbook** [comment]
As said, there is a FH-wide project to provide permament online storage for theses (full text + supplementary data). If this should (ever) materialize it will be the solution of choice. Already checking ...

**Comment by jrappen** [comment]
Should be possible to add a zip-file attachment to generated PDFs?

**Comment by hochleitner** [comment]
That is an interesting approach, @jrappen. I will give it a try. However, when doing a web search on the topic, quite a few Adobe Acrobat related topics come up that seem to indicate that Acrobat is invoking certain security restrictions when it comes to PDFs with such embedded content. This might make it difficult to handle for users trying to access the data.

**Comment by imagingbook** [comment]
Even if this is technically possible, it would not solve our problem. First, some supplementary data (e.g., videos) are simply too large and would bloat the PDF immensely. Second, the old CD/DVD also served as "safe" backup container for the PDF itself.

**Comment by hochleitner** [comment]
Since the university made a decision to stick with physical media, I will close this issue for now.
