### ISSUE TITLE
Set up a Git-Remote on Overleaf

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#30]
To publish the thesis template on Overleaf, the intended approach is (see https://www.overleaf.com/help/230-how-do-i-push-a-new-project-to-overleaf-via-git#.WMqDlE13HCM):

1. create a new Latex project on Overleaf,
2. find out its Git URL (in "share"),
3. add this URL as an additional 'remote' in your local Git repo,
4. merge and 
5. push to the overleaf remote.

Two limitations came up: (a) I could not merge the two repos properly, (b) there is a (undocumented) limitation of max. 60 files for free Overleaf accounts (too few for the complete template).

**Comment by hochleitner** [comment]
Maybe the department needs to buy a license? ;)

**Comment by imagingbook** [comment]
This would not solve the problem because users who want to copy the project will see the same limitations.

**Comment by hochleitner** [comment]
That makes it difficult. Splitting it into two repositories doesn't make sense either und we probably can't also just push parts of it to Overleaf (e.g. only the English version). Hmm...

**Comment by jrappen** [comment]
@imagingbook Using the steps in #36 might help?

**Comment by imagingbook** [comment]
Considered obsolete after 179811522dfa1a930dc5956ab24371f4e120ab82
