### ISSUE TITLE
Change title font for article, lab report and term report

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#32]
Those documents still show serif headings. We should probably change those to match the style of hgbthesis completely. 

The TOC for the term report also needs to be adapted, right now the sans serif fonts for chapters only apply to hgbthesis documents.

**Comment by imagingbook** [comment]
@hochleitner Can we close this issue?

**Comment by imagingbook** [comment]
Accomplished by #45

**Comment by hochleitner** [comment]
Yes, perfect. Totally forgot about this since the PR was merged. Thanks.
