### ISSUE TITLE
Overleaf auto-import link

### ISSUE THREAD

**Issue by jrappen** [Digital-Media/HagenbergThesis#36]
You can use links like:

```text
https://www.overleaf.com/docs?snip_uri=https://github.com/user/project/archive/master.zip
```

to automatically import zip files into Overleaf. I suggest changing the links in the README.

---

/cc @hochleitner

**Comment by imagingbook** [comment]
Implemented by 179811522dfa1a930dc5956ab24371f4e120ab82
