### ISSUE TITLE
@software biblatex Entry Type überdenken

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#4]

**Comment by imagingbook** [comment]
Currently we list ``@software`` items under "Films and audio-visual media" -- which seems inappropriate in general (though perhaps OK for computer games). Then again, the ``@software`` tag may be useful for all sorts of APIs that are frequently referenced now.
I can think of at least 2 options:

1. Create a new reference section "Software" which lists ``@software`` entries only (including games, APIs, etc.).
2. Change the existing section name from "Films and audio-visual media" to "Software and audio-visual media" (e.g.), and list ``@software`` entries in this section.

@hochleitner Any comments?

**Comment by hochleitner** [comment]
According to the biblatex manual, the `type` attribute can be used for custom entry types such as `@software`. We could introduce it to specify the type of software more closely and assign different types of software to different sections?

**Comment by imagingbook** [comment]
What different types of software entries do you have in mind that should not be listed in a common "Software" section?

**Comment by hochleitner** [comment]
No, I meant we could use the `type` field to distinguish e.g. games from APIs and assign them to different sections and still use `@software` for both.

A separate software section is fine for me too and it's probably easier.

By the way, biblatex has entry types for things like images and music (a more specific audio) as well. Should we employ those as well or is this just too much?

**Comment by imagingbook** [comment]
Understood, but I am uncertain to which extent common biblatex styles offer stable support for the subtyping scheme. Same for ``@image``, ``@music`` etc. I suggest to keep things simple, since most bibliography-related problems lie elsewhere.

Think I like the separate "Software" section -- should this include computer games or should they stay in ``avmedia``?

**Comment by imagingbook** [comment]
Implemented by PR #47
