### ISSUE TITLE
Go CTAN

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#54]
It's time now ...

**Comment by hochleitner** [comment]
Haha, told it would happen rather sooner than later. 😉

**Comment by imagingbook** [comment]
I know, but this (bold) step is much simpler with the new setup.

**Comment by martinharrer** [comment]
?We are moving forward to a bright new future of master and bachelor thesis and internship reports


;-)


--

DI Martin Harrer
Medientechnik und -design/Digitale Medien
Fakultät für Informatik, Kommunikation und Medien
FH OÖ Studienbetriebs GmbH
Softwarepark 11
4232 Hagenberg/Austria

Telefon:+43 (0)50804-22128
Fax: +43 (0)50804-22199
Skype: harrer.martin
E-Mail: martin.harrer (at) fh-hagenberg.at
web: www.fh-ooe.at



Firmenbuchgericht/Court of registry: Landesgericht Wels
Firmenbuchnummer/Company registration: FN 205986 X


Bitte nur ausdrucken, wenn es wirklich nötig ist.
________________________________
Von: Wilhelm Burger <notifications@github.com>
Gesendet: Samstag, 21. Oktober 2017 12:48
An: Digital-Media/HagenbergThesis
Cc: Subscribed
Betreff: Re: [Digital-Media/HagenbergThesis] Go CTAN (#54)


I know, but this (bold) step is much simpler with the new setup.

-

**Comment by imagingbook** [comment]
Setup and manual installed by PR #55. First submission to CTAN was released today.
