### ISSUE TITLE
Bachelor thesis: make descriptive fields more flexible

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#62]
From: Teringl Nico - S1510306038 
Sent: Donnerstag, 14. Dezember 2017 16:39
To: Burger Wilhelm
Subject: Bachelor Vorlage LaTeX

Sehr geehrter Herr Burger,

da uns Herr Bogner mitgeteilt hat, dass im Zuge einer Studienplanänderung die Angabe des Kurses - in dem wir unsere Bakk-Arbeit schreiben (Seminar zur Bachelorarbeit) - nicht mehr notwendig ist, wollte ich Sie fragen, wie ich das aus dem LaTeX Dokument entfernen kann?
Ich habe vergeblich versucht, die Zeile „\coursetitle{Seminar zur Bachelorarbeit}“ auszukommentieren, denn dann schreibt er dass er den Kurstitel nicht mehr findet!

Danke im Voraus,
Nico Teringl

**Comment by nteringl** [comment]
Hi!
So I solved this on my own!
**How to delete the part "Seminar zur Bachelorarbeit":**

1. Find the file "**hgbthesis.cls**" in the LaTeX folder from the thesis.
![1](https://user-images.githubusercontent.com/34911782/34407947-509d4a04-ebc1-11e7-80e6-6b5bc712392f.PNG)


2. Go to line **451**, where it says: "Advisor Pages in English and German"
![2](https://user-images.githubusercontent.com/34911782/34407948-50b68690-ebc1-11e7-8076-261c6818de74.PNG)


3. You need to keep in mind if you're writing the English or German version of the thesis and therefore edit the German or English section.
4. As you can see, you can easliy comment out the parts not needed by placing a "%" at the beginning of the line!
![3](https://user-images.githubusercontent.com/34911782/34407946-5082dd04-ebc1-11e7-8b94-b2f34d3693ba.PNG)

5. The advisor should remain on this page, so you have to make sure, that it is centered or placed on the botton of the page using the "**\vspace**"-command!

**Comment by hochleitner** [comment]
This has been already implemented in October 2019 in d425de4e09a292896c56ad8e037c778bc7856469 (along with the removal of other now unnecessary fields).

So I'm closing this issue.
