### ISSUE TITLE
Biber numbers all references with "0"

### ISSUE THREAD

**Issue by ha11owed** [Digital-Media/HagenbergThesis#65]
When running biber/pdflatex, all the references are numbered with "0".
The links work correctly. Also the backlinks.

I am using Miktex 2.9 (with the latest updates as of today)

Changing in hgbbib.sty the option defernumbers=true to false fixed the problem:
`\ExecuteBibliographyOptions{bibwarn=true,sortcites=true,defernumbers=false,isbn=false,doi=false,backref=true}`

Why is this not the default? Or what options should one use in order to make the generation of references work with the original options?

**Comment by imagingbook** [comment]
This behavior is normal. References should be resolved correctly after another Latex/Biber run (3 runs are typically needed).
