### ISSUE TITLE
Chapter/Section Font cannot be changed

### ISSUE THREAD

**Issue by nteringl** [Digital-Media/HagenbergThesis#66]
I have a problem, that I cannot change the font of the **chapters/sections**, even if I change all "**\sffamily**" parts of the .cls and .sty files to "**\rmfamily**" (I want to use Roman instead of Sans Serif). The text has changed into Roman, as I wanted to, but the chapters/section dont change!

**Comment by nteringl** [comment]
# So, once again I solved this by myself!

## Here's a short overview of how to change the font of the **Bachelor Thesis**:

1. Open following files in Notepad++: "**hgb.sty**", "**hgbheadings.sty**", "**hgblistings.sty**" und "**hgbthesis.cls**". 
![1](https://user-images.githubusercontent.com/34911782/34873126-2cd183e0-f794-11e7-8291-a78fb9d1ed88.PNG)
2. Press **Ctrl + F** to open "**Search**" and select the "**Replace**" mode.
3. Replace "**sffamily**" with "**rmfamily**" as shown in the following picture! (Keep in mind to **NOT** have selected the option: "**Nur ganze Wörter suchen**" / "**Only search for complete words**"!!)
![2](https://user-images.githubusercontent.com/34911782/34873180-6180dac8-f794-11e7-82cc-ceedcff58a96.PNG)
4. Replace "**sf**" with "**rm**" as shown in the following picture! (Keep in mind to **SELECT** the option: "**Nur ganze Wörter suchen**" / "**Only search for complete words**"!!)
![3](https://user-images.githubusercontent.com/34911782/34873214-78dbacd4-f794-11e7-8f00-9e174a65e675.PNG)
5. You may need to delete the generated files, and recompile!
6. Finish

## Other fonts
Of course you can choose another font as well, then please refer to the "**titlesec**" package documentation ([http://tug.ctan.org/tex-archive/macros/latex/contrib/titlesec/titlesec.pdf](url))!
This refers to the changes you made by replacing the "**sf**" with "**rm**".
You also have to make sure that you change the "**rmfamily**" correctly as well!

**Comment by imagingbook** [comment]
Obviously the fix was not difficult to find ... Sorry that we do not have the resources to address personal preferences but will only consider real "issues".
