### ISSUE TITLE
Remove advisorpage - hyperref problem?

### ISSUE THREAD

**Issue by student0815** [Digital-Media/HagenbergThesis#67]
Hi,

thanks for sharing this great template. I've used it for a lot of my courses and now for my thesis which is almost done. I've set some modifications and tried to bundle issues with the template. Fortunately there's nothing to bundle because I've only one issue : how can I completely remove the advisorpage without mixing up the page numbering? 

Thanks, 

Chris

**Comment by imagingbook** [comment]
This should be very easy: In file ``hgbthesis.cls`` (starting in line 578) simple remove the ``\@advisorpage`` line, i.e.,
````
\renewcommand{\@bachelortitlepages}{
	\@bachelortitle
%	\@advisorpage
	\@declarationpage
}
````
Not quite sure what you mean by "mixing  up page numbering" ...

**Comment by student0815** [comment]
Thanks for the quick response. I also tried commenting out the \@advisorpage line. But when I build the document, I get the following warning (TeXstudio):

```
pdfTeX warning (ext4): destination with the same identifier (name{page.i}) has 
been already used, duplicate ignored
<to be read again> 
                   \relax 
l.96 \tableofcontents
                      [1
```

Can I ignore this warning?

**Comment by imagingbook** [comment]
I see. I can reproduce this problem on MikTeX, which appears to be unstable at the moment. The problem does not show on Overleaf. Do you see the ToC and the list of references?

**Comment by student0815** [comment]
Yes, I see the ToC and the list of references/bibliography.

**Comment by imagingbook** [comment]
OK, then I suggest to ignore the warning for now. I am not sure how soon I can find/fix the problem as long as MikTeX is unstable.

**Comment by student0815** [comment]
Ok, I'll follow your suggestion. Thanks for support on weekend!

**Comment by imagingbook** [comment]
Try the following: In file ``hgb.sty`` (line 67 ff) modify hypersetup to
````
\hypersetup{
	linktocpage = true,				% make page number, not text, be link on TOC, LOF and LOT 
	colorlinks = false,				% don't uses colored links (because this shows up in printing!) 
	pdfborder = {0 0 0.5},			% use a thinner (0.5pt) border around all PDF links
	allbordercolors = {0 0 0.8},	% dark blue border for all types of links
	breaklinks = true,				% allow links to break over lines by making links over multiple lines
	hypertexnames = false
}	%see https://www.tug.org/applications/hyperref/manual.html
````
Only ``hypertexnames=false`` was added. Let me know if the warning disappears.

**Comment by student0815** [comment]
Don't forget to mention the comma one line above.
I added:
```
breaklinks = true,				% allow links to break over lines by making links over multiple lines
hypertexnames = false
```
in `hgb.sty` file and comment out the `\@advisorpage` line in `hgbthesis.cls`. 
No warnings anymore. 
Huge thanks!

**Comment by imagingbook** [comment]
But the comma was there, no? ;-) 
Brought MikTeX back to life with a fresh 64-bit install (32-bits not supported any longer?).

Unfortunately ``hypertexnames = false`` introduces another problem: page links may get confused (e.g., page "vi" is used instead of "6"). I will upload another fix today ``pageanchor=false`` for the title pages.
