### ISSUE TITLE
Add a beamer-based slide example

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#68]
Would be helpful to have a minimal example setup for ``beamer`` based slides using the ``hagenberg-thesis`` style files. At the moment there is a package clash with ``hyperref``.

**Comment by hochleitner** [comment]
Is this still something that you want to implement, @imagingbook? Maybe another wiki article? Otherwise, I suggest closing the issue.

**Comment by imagingbook** [comment]
No, this issue is obsolete. If needed at all, wiki is the place.
@hochleitner Greetings from the Greek beaches ....
