### ISSUE TITLE
Add predefined (named) colors

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#82]
Load the xcolor package with a set predefined set of named colors (e.g., svgnames) or define a separate (non-conflicting) set of colors?

**Comment by hochleitner** [comment]
What would these colors be used for? Images? Colored listings?

**Comment by imagingbook** [comment]
One usage would be to provide consistent coloring in illustrations done with LaTeX. I would also like to have named colors available, e.g., for highlighting text (though not in any thesis-related documents). Currently the `hagenberg` bundle loads the `xcolor` package without specifying any named colors  and thus only the (marginally useful) core colors are available. If it is possible to reload `xcolor` with different options inside my own documents (using `hgb`) this may be a good solution. Not sure this can be done though ...

**Comment by imagingbook** [comment]
Problem solved: The ``hagenberg`` styles load the ``xcolor`` package without any options. Sets of named colors can still be made available by loading the `xcolor` package **before** any of the `hagenberg` styles, e.g.,
````
\documentclass[...]{...}
\usepackage[dvipsnames,svgnames,x11names]{xcolor}   % use all predefined named colors
\usepackage[german]{hgb}
\usepackage{hgbmath}
...
````
No further action required.
