### ISSUE TITLE
change in citation style 

### ISSUE THREAD

**Issue by epixner** [Digital-Media/HagenbergThesis#86]
hy, 
how can i make changes in the text of the citation? 
i use the HGB-thesis (master) in german language. 

**i want to have a citation in text and also parentized like this:** 

> Dabei gibt es nach Lague **et al.** (2013, S. 5) drei  Quellen ...

instead of this: 

> Dabei gibt es nach Lague **u.a.** (2013, S. 5) drei Quellen ...

this is the header of my bib.sty-file: 

```

%% --------------- Bibliography setup --------------------------------------

\usepackage{csquotes}	% recommended for biblatex
%\usepackage[babel,german=quotes]{csquotes}	% utf8-change ??

%utf8-change
%Note: biblatex with bibtex backend is frozen at version 1.7.
% orginal style = numeric-comp
% change to style=authoryear in Final version!!! (instead of =draft)
\usepackage[style=authoryear,backend=bibtex,maxcitenames=2,bibencoding=auto]{biblatex}[2013/01/10] %utf8-change

\ExecuteBibliographyOptions{bibwarn=true,sortcites=true,defernumbers=true,isbn=false,doi=false,backref=true}
```

Dokumetclass is the following:
`\documentclass[master,german]{hgbthesis}`

thanks and regards 
pixi

**Comment by imagingbook** [comment]
The main intention of ``hgbthesis`` is to provide a standard "out-of-the-box" setup to users who do not have the time or skills to fiddle with LaTeX details. Anyone is free to modify this setup but unfortunately we cannot provide support for individual preferences. I suggest to consult the corresponding documentation (https://ctan.org/pkg/biblatex, https://ctan.org/pkg/biber).
