### ISSUE TITLE
Add listings environment for "PythonCode"

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#88]
There is frequent need to list Python code. Perhaps the modification of `hgblistings.sty` by Christina Grafeneder is useful as a starting point:
[hgblistings.txt](https://github.com/Digital-Media/HagenbergThesis/files/3300987/hgblistings.txt)

**Comment by hochleitner** [comment]
This was fixed in afed5fbc69d8c926dda5d1e9dc8dbb2c4c162025. Manual and example document were also updated to reflect the changes.
