### ISSUE TITLE
Biblatex: check use/output of "issue" field

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#90]
Check the comment on use of `issue` field for multiple months (p. 52 in thesis tutorial). Strange output is produced. It should not be used in place of the `number` field.

**Comment by hochleitner** [comment]
> Die Angabe einer Ausgabe für *mehrere* Monate ist in biblatex nicht mehr
über das Feld `month` möglich, denn dieses darf nur mehr *einen* Wert enthalten.

Is that (still) true? I tried replacing `issue` with `number` in the `Guttman2001` entry and I see no errors:

```
@article{Guttman2001,
  author={Guttman, Erik},
  title={Autoconfiguration for {IP} Networking},
  journal={IEEE Internet Computing},
  volume={5},
  number={5/6},
  year={2001},
  pages={81-86},
  hyphenation={english}
}
```
Output looks like this:
![guttmann-number](https://user-images.githubusercontent.com/2236807/75504646-60800780-59d9-11ea-87e8-ad6504a2c7d2.png)

as opposed to this (still with `issue`):
![guttmann-issue](https://user-images.githubusercontent.com/2236807/75504656-6675e880-59d9-11ea-8555-c2146ceac74c.png)

So what is correct/better in this case?

**Comment by imagingbook** [comment]
Not quite sure, but the ``number`` version looks OK:
Q: Why exactly this example? The correct entry here is ``number={3}`` (https://ieeexplore.ieee.org/abstract/document/935181)...

**Comment by hochleitner** [comment]
> Q: Why exactly this example? The correct entry here is `number={3}` (https://ieeexplore.ieee.org/abstract/document/935181)...

I have no idea, to be honest. I did not add the example but it was the one that is mentioned with the multiple months. If this is wrong anyway, we need to find another example or remove it altogether and maybe add an entry to the wiki how to deal with this situation.

**Comment by imagingbook** [comment]
`biblatex` since version 3.12 allows non-numeric entries in the `number` field, so this field may be used for multiple issues. See also these discussions: https://tex.stackexchange.com/questions/418590/biblatex-doesnt-recognize-the-journals-issue-number-when-filled-by-a-non-numer and https://github.com/plk/biblatex/issues/726.
Cleaned up and added a new example to the thesis turorial (commit 8bd2b3ea801ec841304d4135e2ea9ef9a88c9a09).
