### ISSUE TITLE
Issue warning if old style files are used

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#94]
We should check if the thesis style files used in the current setup are outdated (e.g., older than 6 months). It sometimes happens that *very* old versions are used accidentally.

**Comment by imagingbook** [comment]
The 'datetime' package (used so far) has become obsolete. Will replace with 'datetime2'.

**Comment by hochleitner** [comment]
Who comes up with such ingenious names for packages? 😉

**Comment by imagingbook** [comment]
Implemented by commit 2bc1895.
