### ISSUE TITLE
Error with \DTMgermanmonthname

### ISSUE THREAD

**Issue by TheGreen0ne** [Digital-Media/HagenbergThesis#97]
https://github.com/Digital-Media/HagenbergThesis/blob/c359e9aeb40946f13f0fcdfbcbc32da697d15627/ctan/hagenberg-thesis/latex/hgbthesis.cls#L179
it seems the usage of \DTMgermanmonthname with [] creates an error at least with texlive
a workaround/fix would be using {} instad of []
in the [datetime2 package documentation](https://www.ctan.org/pkg/datetime2) it is also used with {}

**Comment by imagingbook** [comment]
Fixed by commit a47a521b5b872134190c97ae175ebb12586be3df
Thanks for reporting this.
